server:
  port: 8080
spring:
  application:
    name: gestion-alumnos-api
  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5432/gestion_alumnos}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
