--
-- PostgreSQL database dump
--

\restrict 07ehcx242TqIbHmnGQXNwTqXCCYRvGDiWRdne0fpj9nVbu1w0cDkDo2ahwNzG52

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.notas DROP CONSTRAINT IF EXISTS fkkr556mopx96m5okly6ahy70jc;
ALTER TABLE IF EXISTS ONLY public.notas DROP CONSTRAINT IF EXISTS fka9lly8ij9aui59h8x6sk3b9yr;
ALTER TABLE IF EXISTS ONLY public.alumnos DROP CONSTRAINT IF EXISTS ukrrq96s55g45kywh0ypeed2u1v;
ALTER TABLE IF EXISTS ONLY public.materias DROP CONSTRAINT IF EXISTS uk7sbwncy96knj65wg87rmjayy5;
ALTER TABLE IF EXISTS ONLY public.notas DROP CONSTRAINT IF EXISTS uk6bg9f9x660dygugn1my6m0re3;
ALTER TABLE IF EXISTS ONLY public.notas DROP CONSTRAINT IF EXISTS notas_pkey;
ALTER TABLE IF EXISTS ONLY public.materias DROP CONSTRAINT IF EXISTS materias_pkey;
ALTER TABLE IF EXISTS ONLY public.alumnos DROP CONSTRAINT IF EXISTS alumnos_pkey;
DROP TABLE IF EXISTS public.notas;
DROP TABLE IF EXISTS public.materias;
DROP TABLE IF EXISTS public.alumnos;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alumnos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.alumnos (
    id bigint NOT NULL,
    apellido character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    fecha_nacimiento date,
    nombre character varying(255) NOT NULL
);


ALTER TABLE public.alumnos OWNER TO postgres;

--
-- Name: alumnos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.alumnos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumnos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: materias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.materias (
    id bigint NOT NULL,
    codigo character varying(255) NOT NULL,
    creditos integer NOT NULL,
    nombre character varying(255) NOT NULL
);


ALTER TABLE public.materias OWNER TO postgres;

--
-- Name: materias_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.materias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notas (
    id bigint NOT NULL,
    fecha_registro date NOT NULL,
    valor double precision NOT NULL,
    alumno_id bigint NOT NULL,
    materia_id bigint NOT NULL,
    CONSTRAINT notas_valor_check CHECK (((valor >= (0)::double precision) AND (valor <= (5)::double precision)))
);


ALTER TABLE public.notas OWNER TO postgres;

--
-- Name: notas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: alumnos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.alumnos (id, apellido, email, fecha_nacimiento, nombre) FROM stdin;
1	Pérez	juan.david@email.com	2000-05-15	Juan David
2	Pérez	juan.perez@email.com	2000-05-15	Juan
\.


--
-- Data for Name: materias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.materias (id, codigo, creditos, nombre) FROM stdin;
2	BD202	4	Bases de Datos
1	JAVA101	4	Programación Java
\.


--
-- Data for Name: notas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notas (id, fecha_registro, valor, alumno_id, materia_id) FROM stdin;
2	2026-01-15	4.5	1	1
3	2026-01-15	3.8	1	2
\.


--
-- Name: alumnos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.alumnos_id_seq', 3, true);


--
-- Name: materias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.materias_id_seq', 3, true);


--
-- Name: notas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notas_id_seq', 4, true);


--
-- Name: alumnos alumnos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alumnos
    ADD CONSTRAINT alumnos_pkey PRIMARY KEY (id);


--
-- Name: materias materias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materias
    ADD CONSTRAINT materias_pkey PRIMARY KEY (id);


--
-- Name: notas notas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notas
    ADD CONSTRAINT notas_pkey PRIMARY KEY (id);


--
-- Name: notas uk6bg9f9x660dygugn1my6m0re3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notas
    ADD CONSTRAINT uk6bg9f9x660dygugn1my6m0re3 UNIQUE (alumno_id, materia_id);


--
-- Name: materias uk7sbwncy96knj65wg87rmjayy5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materias
    ADD CONSTRAINT uk7sbwncy96knj65wg87rmjayy5 UNIQUE (codigo);


--
-- Name: alumnos ukrrq96s55g45kywh0ypeed2u1v; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alumnos
    ADD CONSTRAINT ukrrq96s55g45kywh0ypeed2u1v UNIQUE (email);


--
-- Name: notas fka9lly8ij9aui59h8x6sk3b9yr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notas
    ADD CONSTRAINT fka9lly8ij9aui59h8x6sk3b9yr FOREIGN KEY (alumno_id) REFERENCES public.alumnos(id);


--
-- Name: notas fkkr556mopx96m5okly6ahy70jc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notas
    ADD CONSTRAINT fkkr556mopx96m5okly6ahy70jc FOREIGN KEY (materia_id) REFERENCES public.materias(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 07ehcx242TqIbHmnGQXNwTqXCCYRvGDiWRdne0fpj9nVbu1w0cDkDo2ahwNzG52

